apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: register-app
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: register-app
  endpoints:
  - port: http
    path: /actuator/prometheus
